export const API_BASE_URL =
  process.env.NEXT_PUBLIC_API_BASE_URL ?? "https://cpd.enamelacademy.co.uk";

export const API_PATHS = {
  auth: {
    register: "/wp-json/reactapi/v1/register",
    login: "/wp-json/reactapi/v1/login",
    logout: "/wp-json/reactapi/v1/logout",
    validateToken: "/wp-json/reactapi/v1/validate-token",
    forgotPassword: "/wp-json/reactapi/v1/forgot-password",
    verifyOtp: "/wp-json/reactapi/v1/verify-otp",
    resetPassword: "/wp-json/reactapi/v1/reset-password",
    validateResetToken: "/wp-json/reactapi/v1/validate-reset-token",
  },
  user: {
    me: "/wp-json/reactapi/v1/user",
    update: "/wp-json/reactapi/v1/user/update",
    changePassword: "/wp-json/reactapi/v1/user/change-password",
  },
  dashboard: {
    root: "/wp-json/reactapi/v1/dashboard",
    stats: "/wp-json/reactapi/v1/dashboard/stats",
    continueLearning: "/wp-json/reactapi/v1/dashboard/continue-learning",
    courseById: (id: string | number) => `/wp-json/reactapi/v1/dashboard/courses/${id}`,
  },
  courses: {
    library: "/wp-json/reactapi/v1/courses/library",
    details: "/wp-json/reactapi/v1/courses/",
    list: "/wp-json/reactapi/v1/courses",
    ongoing: "/wp-json/reactapi/v1/courses/ongoing",
    categories: "/wp-json/reactapi/v1/courses/categories",
    filters: "/wp-json/reactapi/v1/courses/filters",
    enroll: (id: string | number) => `/wp-json/reactapi/v1/courses/enroll/${id}`,
    reflection: (id: string | number) => `/wp-json/reactapi/v1/courses/${id}/reflection`,
    reflections: (id: string | number) => `/wp-json/reactapi/v1/courses/${id}/reflections`,
    feedback: (id: string | number) => `/wp-json/reactapi/v1/courses/${id}/feedback`,
  },
  dental: {
    roles: "/wp-json/reactapi/v1/dental/roles",
    permissions: (role: string) => `/wp-json/reactapi/v1/dental/permissions/${role}`,
  },
  pdp: {
    root: "/wp-json/reactapi/v1/pdp",
    byId: (id: string | number) => `/wp-json/reactapi/v1/pdp/${id}`,
    status: (id: string | number) => `/wp-json/reactapi/v1/pdp/${id}/status`,
    stats: "/wp-json/reactapi/v1/pdp/stats",
    skillsLibrary: "/wp-json/reactapi/v1/pdp/skills-library",
    objectives: (id: string | number) => `/wp-json/reactapi/v1/pdp/${id}/objectives`,
    skills: (id: string | number) => `/wp-json/reactapi/v1/pdp/${id}/skills`,
    activities: (id: string | number) => `/wp-json/reactapi/v1/pdp/${id}/activities`,
    milestones: (id: string | number) => `/wp-json/reactapi/v1/pdp/${id}/milestones`,
    reflection: (id: string | number) => `/wp-json/reactapi/v1/pdp/${id}/reflection`,
    linkCourse: (id: string | number) => `/wp-json/reactapi/v1/pdp/${id}/link-course`,
  },
  certificates: {
    course: (id: string | number) => `/wp-json/reactapi/v1/certificates/course/${id}`,
    myCertificates: "/wp-json/reactapi/v1/certificates/my-certificates",
    check: (id: string | number) => `/wp-json/reactapi/v1/certificates/check/${id}`,
    preview: (id: string | number) => `/wp-json/reactapi/v1/certificates/preview/${id}`,
    verify: "/wp-json/reactapi/v1/certificates/verify",
  },
  assignment: {
    courseAssignments: (id: string | number) => `/wp-json/reactapi/v1/courses/${id}/assignments`,
    courseQuizzes: (id: string | number) => `/wp-json/reactapi/v1/courses/${id}/quizzes`,
    courseAssessments: (id: string | number) => `/wp-json/reactapi/v1/courses/${id}/assessments`,
    assignmentStats: (id: string | number) => `/wp-json/reactapi/v1/courses/${id}/assignment-stats`,
    quizStats: (id: string | number) => `/wp-json/reactapi/v1/courses/${id}/quiz-stats`,
    assignmentDetails: (id: string) => `/wp-json/reactapi/v1/assignments/${id}`,
    quizDetails: (id: string | number) => `/wp-json/reactapi/v1/quizzes/${id}`,
    quizAttempts: (id: string | number) => `/wp-json/reactapi/v1/quizzes/${id}/attempts`,
  },
  cpd: {
    summary: "/wp-json/reactapi/v1/cpd/summary",
    history: "/wp-json/reactapi/v1/cpd/history",
    analytics: "/wp-json/reactapi/v1/cpd/analytics",
    requirements: (role: string) => `/wp-json/reactapi/v1/cpd/requirements/${role}`,
    logExternal: "/wp-json/reactapi/v1/cpd/log-external",
    generateAuditReport: "/wp-json/reactapi/v1/cpd/generate-audit-report",
  },
  testApi: "/wp-json/reactapi/v1/TESTApi",
} as const;
